ALTER TABLE `hifz_weekly_entries`
  ADD COLUMN `weekLabel` VARCHAR(150) NULL,
  ADD COLUMN `className` VARCHAR(150) NULL,
  ADD COLUMN `sectionName` VARCHAR(150) NULL,
  ADD COLUMN `teacherName` VARCHAR(150) NULL,
  ADD COLUMN `sawal1` INTEGER NULL,
  ADD COLUMN `sawal2` INTEGER NULL,
  ADD COLUMN `sawal3` INTEGER NULL,
  ADD COLUMN `tahajji` INTEGER NULL,
  ADD COLUMN `panja` INTEGER NULL,
  ADD COLUMN `khudKhwani` INTEGER NULL,
  ADD COLUMN `classWork` VARCHAR(150) NULL;
