INSERT IGNORE INTO `permissions` (`permission_key`, `permission_name`, `display_label`, `page_path`, `module_name`, `action`, `sort_order`)
VALUES
  ('branches.view', 'View Branches', 'برانچز دیکھیں', '/branch-management', 'branches', 'view', 10),
  ('branches.create', 'Create Branches', 'برانچ محفوظ کریں', '/branch-management', 'branches', 'create', 20),
  ('branches.update', 'Update Branches', 'برانچ تبدیل کریں', '/branch-management', 'branches', 'update', 30),
  ('branches.delete', 'Delete Branches', 'برانچ غیر فعال کریں', '/branch-management', 'branches', 'delete', 40),
  ('classes.view', 'View Classes', 'جماعتیں دیکھیں', '/class-management/Classes', 'classes', 'view', 10),
  ('classes.create', 'Create Classes', 'جماعت محفوظ کریں', '/class-management/Classes', 'classes', 'create', 20),
  ('classes.edit', 'Edit Classes', 'جماعت تبدیل کریں', '/class-management/Classes', 'classes', 'edit', 30),
  ('classes.delete', 'Delete Classes', 'جماعت حذف کریں', '/class-management/Classes', 'classes', 'delete', 40),
  ('sections.view', 'View Sections', 'سیکشن دیکھیں', '/class-management/sections', 'sections', 'view', 10),
  ('sections.create', 'Create Sections', 'سیکشن محفوظ کریں', '/class-management/sections', 'sections', 'create', 20),
  ('sections.edit', 'Edit Sections', 'سیکشن تبدیل کریں', '/class-management/sections', 'sections', 'edit', 30),
  ('sections.delete', 'Delete Sections', 'سیکشن حذف کریں', '/class-management/sections', 'sections', 'delete', 40),
  ('sessions.view', 'View Sessions', 'سیشن دیکھیں', '/class-management/session', 'sessions', 'view', 10),
  ('subjects.view', 'View Subjects', 'مضامین دیکھیں', '/class-management/subjects', 'subjects', 'view', 10),
  ('fees.view', 'View Fees', 'فیس دیکھیں', '/students/fees', 'fees', 'view', 10),
  ('fees.create', 'Create Fees', 'فیس محفوظ کریں', '/students/fees', 'fees', 'create', 20),
  ('fees.edit', 'Edit Fees', 'فیس تبدیل کریں', '/students/fees', 'fees', 'edit', 30),
  ('fees.delete', 'Delete Fees', 'فیس حذف کریں', '/students/fees', 'fees', 'delete', 40),
  ('fees.details.view', 'View Fee Details', 'فیس تفصیل دیکھیں', '/students/details/:id', 'fees', 'view', 50),
  ('reports.view', 'View Reports', 'رپورٹس دیکھیں', '/finance/reports/financial-statements', 'reports', 'view', 10),
  ('attendance.mark', 'Mark Attendance', 'حاضری درج کریں', '/students/attendance', 'attendance', 'create', 20),
  ('students.update', 'Update Student Records', 'طالب علم تبدیل کریں', '/students/list', 'students', 'update', 30),
  ('teachers.update', 'Update Teacher Records', 'استاد تبدیل کریں', '/teachers/list', 'teachers', 'update', 30),
  ('store.categories.view', 'View Store Categories', 'اسٹور کیٹیگریز دیکھیں', '/store/categories', 'store', 'view', 11),
  ('store.items.view', 'View Store Items', 'اسٹور اشیاء دیکھیں', '/store/items', 'store', 'view', 12),
  ('store.items.create', 'Create Store Items', 'اسٹور شے محفوظ کریں', '/store/items', 'store', 'create', 22),
  ('store.items.edit', 'Edit Store Items', 'اسٹور شے تبدیل کریں', '/store/items', 'store', 'edit', 32),
  ('store.items.delete', 'Delete Store Items', 'اسٹور شے حذف کریں', '/store/items', 'store', 'delete', 42),
  ('store.purchases.view', 'View Store Purchases', 'خریداری دیکھیں', '/store/purchases', 'store', 'view', 13),
  ('store.purchases.create', 'Create Store Purchases', 'خریداری محفوظ کریں', '/store/purchases', 'store', 'create', 23),
  ('store.stock_issues.view', 'View Stock Issues', 'اسٹاک اجراء دیکھیں', '/store/stock-issues', 'store', 'view', 14),
  ('store.returns.view', 'View Store Returns', 'واپسی دیکھیں', '/store/returns', 'store', 'view', 15),
  ('store.damaged_stock.view', 'View Damaged Stock', 'خراب اسٹاک دیکھیں', '/store/damaged-stock', 'store', 'view', 16),
  ('store.suppliers.view', 'View Store Suppliers', 'سپلائرز دیکھیں', '/store/suppliers', 'store', 'view', 17),
  ('store.units.view', 'View Store Units', 'اکائیاں دیکھیں', '/store/units', 'store', 'view', 18);
