ALTER TABLE `students`
    ADD COLUMN `admissionDate` DATETIME(3) NULL,
    ADD COLUMN `admissionFee` DECIMAL(10, 2) NULL,
    ADD COLUMN `caste` VARCHAR(100) NULL,
    ADD COLUMN `cnic` VARCHAR(50) NULL,
    ADD COLUMN `bForm` VARCHAR(50) NULL,
    ADD COLUMN `whatsapp` VARCHAR(50) NULL,
    ADD COLUMN `currentAddress` VARCHAR(255) NULL,
    ADD COLUMN `permanentAddress` VARCHAR(255) NULL,
    ADD COLUMN `district` VARCHAR(150) NULL,
    ADD COLUMN `prevMadrassa` VARCHAR(150) NULL,
    ADD COLUMN `prevSchool` VARCHAR(150) NULL,
    ADD COLUMN `secularEdu` VARCHAR(150) NULL,
    ADD COLUMN `religiousEdu` VARCHAR(150) NULL,
    ADD COLUMN `requiredClass` VARCHAR(150) NULL,
    ADD COLUMN `requiredJamaat` VARCHAR(150) NULL,
    ADD COLUMN `teacherName` VARCHAR(150) NULL,
    ADD COLUMN `medicalCondition` VARCHAR(255) NULL,
    ADD COLUMN `monthlyFee` DECIMAL(10, 2) NULL,
    ADD COLUMN `reside` VARCHAR(20) NULL;
