CREATE TABLE IF NOT EXISTS `teacher_responsibilities` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenant_id` INTEGER NOT NULL,
  `branch_id` INTEGER NULL,
  `branch_scope_key` VARCHAR(50) NOT NULL DEFAULT 'tenant',
  `name` VARCHAR(150) NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'active',
  `created_by` INTEGER NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `teacher_resp_scope_name_unique` (`tenant_id`, `branch_scope_key`, `name`),
  INDEX `teacher_resp_tenant_idx` (`tenant_id`),
  INDEX `teacher_resp_branch_idx` (`branch_id`),
  INDEX `teacher_resp_status_idx` (`status`),
  INDEX `teacher_resp_created_by_idx` (`created_by`),
  CONSTRAINT `teacher_responsibilities_tenant_id_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `teacher_responsibilities_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `teacher_responsibilities_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `admins`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `teacher_assignments` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenant_id` INTEGER NOT NULL,
  `branch_id` INTEGER NOT NULL,
  `branch_scope_key` VARCHAR(50) NOT NULL,
  `teacher_id` INTEGER NOT NULL,
  `subject_id` INTEGER NOT NULL,
  `class_id` INTEGER NOT NULL,
  `section_id` INTEGER NOT NULL,
  `responsibility_id` INTEGER NOT NULL,
  `assignment_scope_key` VARCHAR(255) NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'active',
  `created_by` INTEGER NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `teacher_assign_scope_unique` (`tenant_id`, `branch_id`, `assignment_scope_key`),
  INDEX `teacher_assign_tenant_idx` (`tenant_id`),
  INDEX `teacher_assign_branch_idx` (`branch_id`),
  INDEX `teacher_assign_tenant_branch_idx` (`tenant_id`, `branch_id`),
  INDEX `teacher_assign_teacher_idx` (`teacher_id`),
  INDEX `teacher_assign_subject_idx` (`subject_id`),
  INDEX `teacher_assign_class_idx` (`class_id`),
  INDEX `teacher_assign_section_idx` (`section_id`),
  INDEX `teacher_assign_resp_idx` (`responsibility_id`),
  INDEX `teacher_assign_status_idx` (`status`),
  INDEX `teacher_assign_created_by_idx` (`created_by`),
  CONSTRAINT `teacher_assignments_tenant_id_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `teacher_assignments_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`) ON UPDATE CASCADE,
  CONSTRAINT `teacher_assignments_teacher_id_fkey` FOREIGN KEY (`teacher_id`) REFERENCES `teachers`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `teacher_assignments_subject_id_fkey` FOREIGN KEY (`subject_id`) REFERENCES `subjects`(`id`) ON UPDATE CASCADE,
  CONSTRAINT `teacher_assignments_class_id_fkey` FOREIGN KEY (`class_id`) REFERENCES `classes`(`id`) ON UPDATE CASCADE,
  CONSTRAINT `teacher_assignments_section_id_fkey` FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE CASCADE,
  CONSTRAINT `teacher_assignments_responsibility_id_fkey` FOREIGN KEY (`responsibility_id`) REFERENCES `teacher_responsibilities`(`id`) ON UPDATE CASCADE,
  CONSTRAINT `teacher_assignments_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `admins`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT IGNORE INTO `permissions` (`permission_key`, `permission_name`, `display_label`, `description`, `page_path`, `module_name`, `action`, `sort_order`)
VALUES
  ('teachers.assignments.view', 'View Teacher Assignments', 'مضامین اور ذمہ داریاں دیکھیں', 'Can view teacher subject and responsibility assignments', '/teachers/assignments', 'teachers', 'assignments.view', 176),
  ('teachers.assignments.create', 'Create Teacher Assignments', 'مضامین اور ذمہ داریاں شامل کریں', 'Can create teacher subject and responsibility assignments', '/teachers/assignments', 'teachers', 'assignments.create', 177),
  ('teachers.assignments.edit', 'Edit Teacher Assignments', 'مضامین اور ذمہ داریاں تبدیل کریں', 'Can edit teacher subject and responsibility assignments', '/teachers/assignments', 'teachers', 'assignments.edit', 178),
  ('teachers.assignments.delete', 'Delete Teacher Assignments', 'مضامین اور ذمہ داریاں حذف کریں', 'Can remove teacher subject and responsibility assignments', '/teachers/assignments', 'teachers', 'assignments.delete', 179);
